default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: postgres
  password: qweqwe

development:
  <<: *default
  database: poems_blog_development

test:
  <<: *default
  database: poems_blog_test
